### ISSUE TITLE
localStorage messed up in Android

### ISSUE THREAD

**Issue by szantner** [driftyco/ionic-view-issues#100]
Hi,

Using Ionic View on Android 5.1.1 on a Nexus 10

There seems to be an issue that writing the local storage from the app doesn't get saved. (I usually kill the app since the 3 finger wipe is not working) There seems to be an issue with persistence, since the Ionic View forgets even that my app was downloaded and I have to re-download it every time (Though this is not 100% consistent).

What is even more strange that when I exit to the main screen with the back button and then back to my app, the local storage seems to work, but when I kill the Ionic View app from the task list and restart it, the local storage is gone.

**Comment by simplesmiler** [comment]
Having similar issue with Ionic View on iOS 8.3.
Application inside View always starts with an empty localStorage (except for the View own keys).

**Comment by dimiandre** [comment]
Confirm local storage always empty on iOS 8.4

**Comment by simplesmiler** [comment]
Related: https://github.com/driftyco/ionic-view-issues/issues/117#issuecomment-112072083
