### ISSUE TITLE
Blank app only in ionic view on ios 8 device

### ISSUE THREAD

**Issue by sluchznak** [driftyco/ionic-view-issues#103]
Hello.
I faced with the problem.
My application been run before, but not now.
Now is work on:
1. Android 5.1 device (Nexus 5)
2. Android 5.1 emulator (Nexus 5)
3. Android Ionic View on device
4. iOS 8.3 emulator (iPhone 6)

But it doesn`t work in iPhone 5 (ios 8.3) Ionic View.

p.s.:
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.8.11
Gulp local:   Local version 3.8.11
Ionic Version: 1.0.0
Ionic CLI Version: 1.4.4
Ionic App Lib Version: 0.0.20
ios-deploy version: Not installed
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by robksawyer** [comment]
Anyone fix this? I'm running into it as well in iOS 8.4.1.
