### ISSUE TITLE
Add Contacts and SMS plugins

### ISSUE THREAD

**Issue by nicopace** [driftyco/ionic-view-issues#106]
cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-contacts.git
cordova plugin add https://github.com/cordova-sms/cordova-sms-plugin.git

**Comment by chrisguida** [comment]
+1

**Comment by nicopace** [comment]
Why was this closed? I feel these are pretty essential plugins.

**Comment by simplesmiler** [comment]
@nicopace probably because there is dedicated issue for [plugin requests](https://github.com/driftyco/ionic-view-issues/issues/15).
