### ISSUE TITLE
facebook login with $cordovaFacebook not working

### ISSUE THREAD

**Issue by suroorwijdan** [driftyco/ionic-view-issues#109]
I have integrated native facebook login with cordova facebook plugin. The whole thing works perfectly in ios emulator but not on  iphone with ionicview. 

It fails silently, not able to debug. Anyone else encountered this?

**Comment by nileshlg2003** [comment]
I am not sure if its the same issue, But when I use facebook login on android directly it works well, but same thing on iphone using ionicView silently fails, screen returns to login page after facebook authentication and gets stuck there. I am using  ng-cordova-oauth for facebook Authentication.

**Comment by suroorwijdan** [comment]
@nileshlg2003 to rule out any confusions, i am using the following plugin `https://github.com/Wizcorp/phonegap-facebook-plugin`. 

On IOS emulator it works fine but not on iphone.  On ionic view it doesn't do anything and gets stuck when you call the login function.

**Comment by parkerparker** [comment]
Does anyone has resolve this problem ?
Im having the same issue.
More important, does the app work fine outside of ionic view ?
Thanks !

**Comment by suroorwijdan** [comment]
@parkerparker the app does work outside of ionic view and even in browser. I guess, ionic view doesn't support Facebook Login plugin as of now.

**Comment by parkerparker** [comment]
@suroorwijdan Thanks for your awnser !!

**Comment by tlancina** [comment]
Hey thanks for the issue. The InAppBrowser plugin (what facebook uses for oauth) isn't supported by View at this time, but you can request it be added here: #15.
