### ISSUE TITLE
ngCordova inappbrowser in (ionic view app under iOS) cannot be closed

### ISSUE THREAD

**Issue by style-x7** [driftyco/ionic-view-issues#111]
Hi all,

I'm following the example in http://forum.ionicframework.com/t/inappbrowser-options-not-working/16896/9

And managed to deploy in iOS emulator, the inappbrowser with '_blank' is working with the close button at the bottom of the emulator's screen.

However, when the app is deployed to Ionic View app, in iPhone, the inappbrowser does load the url but the close button cannot be found and thus I can't close the inappbrowser.

Is this an expected behavior (as I read that the Ionic View app itself is also running under inappbrowser? I still hope there's some way to get around this issue.

**Comment by thomasloh** [comment]
Having this issue as well. Any updates?

**Comment by elhamsarikhani** [comment]
Currently inAppBrowser is not supported in ionic view. 
you can check and vote for this issue in here:
https://github.com/driftyco/ionic-view-issues/issues/15

**Comment by tlancina** [comment]
Hey thanks for the issue. InAppBrowser isn't supported by View at this time, but you can request it be added here: #15.
