### ISSUE TITLE
Add ability to externally launch "tel:" links

### ISSUE THREAD

**Issue by adamduren** [driftyco/ionic-view-issues#112]
Phone links work in the Ionic app installed locally if it has the correct `access` directive in the `config.xml` file. They do not appear to be supported in the View app. Can this feature be added?

Here is the `config.xml` entry for reference:
```xml
  <access origin="tel:*" launch-external="yes" />
```

**Comment by ariesmcrae** [comment]
'mailto:' and 'geo:' also don't work in IonicView (and possibly 'sms:' too).

**Comment by rozaydin** [comment]
+1
