### ISSUE TITLE
support windows for debugging ionic view apps

### ISSUE THREAD

**Issue by parliament718** [driftyco/ionic-view-issues#113]
I absolutely love how you can just do ```ionic upload``` and instantly get my app on my iphone!

But how am I supposed to debug it? I'm on windows and all options I have found require to be on OSX.

1) Safari 6 remote debugging - Safari for windows was discontinued at 5.1

2) XCode - nope, on windows

3) ```ionic emulate ios -l -c -s``` nope, on windows

I have a Mac on standby listening for build requests via vs-mda-remote service from the Visual Studio Cordova Tools so I'm able to build an .ipa file on windows, therefore I should be able to run it using ionic.

Perhaps by specifiying the .ipa file

```ionic run "C:\repo\build\myapp.ipa" -l -c -s```

Can we haz this on the roadmap or an alternative solution to debugging an app in ionic-view from windows? Otherwise I have to go with GapDebug, (which allows to do just that; upload my ipa file and debug it from my device).

In fact, the full solution could use vs-mda-remote to do the build as well, so it's fully steamlined:
```ionic build ios```    (if on windows, uses vs-mda-remote to build an ipa file)
```ionic run -l -c -s```  (if on windows, runs the last built .ipa file similar to GapDebug)

**Comment by parliament718** [comment]
I need to debug a certain issue in my app that only occurs on the device through IonicView. Do I have any options at all on windows? I've sucesssfully hooked up GapDebug and the issue is not there anymore when deploying to the device via ipa file. I like the ionicview approach better since I don't actually need to build the ipa, but if I can't debug it I can't really use it.

**Comment by parliament718** [comment]
I'm still stuck on this issue. I cannot replicate the issue anywhere except from within ionicview upload. I am unable to see any debug information like the console or network traffic so I literally have no way to see what's wrong. 

Is there anything at all I can do on Windows to debug this app.

**Comment by simplesmiler** [comment]
@parliament718 you could try [weinre](http://people.apache.org/~pmuellr/weinre/).

It provides you with at least:
- interactive console with log
- elements tree (with limited support for editing html and styles)

Not perfect but something.
