### ISSUE TITLE
bug: Plugins seem hit or miss in Ionic View

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-view-issues#114]
_From @mdridley on May 28, 2015 13:53_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Apps work fine when we publish with Ionic Build. We have been trying to get a more complicated application working for a client on Ionic View so that we can bypass having to put up with TestFlight. However many of the plugins (like the In-App Browser (https://github.com/apache/cordova-plugin-inappbrowser) for when we open up a website) are not working. We have not been able to capture any errors yet, still trying to dig into it, but again, the plugins are working fine with regular deployment. Any ideas would be welcome. Thanks.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3854_

**Comment by tlancina** [comment]
InAppBrowser isn't supported yet, the list of supported plugins are here: http://docs.ionic.io/v1.0/docs/view-usage.
