### ISSUE TITLE
Scandit BarcodeScanner Support

### ISSUE THREAD

**Issue by tpisani** [driftyco/ionic-view-issues#115]
Hey Guys!

Is it possible to also add support for scandit's barcode scanner?https://github.com/Scandit/BarcodeScannerPlugin

I've been using wildabeast's scanner, but the error rate is somewhat high, which gives me some trouble.
https://github.com/wildabeast/BarcodeScanner

Ionic View is already awesome, and this would make my life so much easier.
Thanks for the hard work!

**Comment by tlancina** [comment]
Added it to the list of plugin requests.
