### ISSUE TITLE
Ionic View doesn't load phonegap plugin

### ISSUE THREAD

**Issue by sandraVicom** [driftyco/ionic-view-issues#116]
I have a app with a CouchBase plugin for cordova. When I run it directly into a device it works fine. The problem arises when I run it from Ionic View. The Ionic View doesn't load the CouchBase plugin and it crashes. 
Any idea why how to solve this problem.
Thank you.

**Comment by bradmartin** [comment]
I'm not 100% certain what you actually mean by plugin, you mention phonegap plugin in the title but just Couchbase plugin in the message so sorry if I'm mistaken. From what I recall only certain Cordova plugins are supported in the Ionic View app, they are listed on the site as they've updated it not long ago for a couple of new capabilities. Hope that helps.

**Comment by tlancina** [comment]
Added Couchbase plugin to the plugin requests list.
