### ISSUE TITLE
Ionic adds blank space below the header when using ionic uplaod

### ISSUE THREAD

**Issue by strenev** [driftyco/ionic-view-issues#119]
Hello, when I try to upload my app to Ionic View, the consequence is that the html or css somehow brakes and blank space appears below the header.

**Comment by simplesmiler** [comment]
May be related to https://github.com/driftyco/ionic-cli/issues/452

**Comment by bradmartin** [comment]
@simplesmiler correct. I just posted a work around that works for me to that issue https://github.com/driftyco/ionic-cli/issues/452

**Comment by tlancina** [comment]
Should have been fixed with https://github.com/driftyco/ionic-app-lib/commit/b757d3866176d531de7bb6806bbeb29882f6010a.  If not, feel free to reopen https://github.com/driftyco/ionic-cli/issues/452 with steps to reproduce, thanks!
