### ISSUE TITLE
Unexpected token < (CLI v1.3.2)

### ISSUE THREAD

**Issue by RomanMinkin** [driftyco/ionic-view-issues#12]
Hi guys,

Happens for me after i added `ionicons`  with command
```bash
ionic add ionicons
```

Info
```
ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.26
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a
ios-sim version: 3.1.1
```

I also changed `ionic.app.scss` we i can use `ionicons` fonts:
```scss
/*
To customize the look and feel of Ionic, you can override the variables
in ionic's _variables.scss file.

For example, you might change some of the default colors:

$light:                           #fff !default;
$stable:                          #f8f8f8 !default;
$positive:                        #387ef5 !default;
$calm:                            #11c1f3 !default;
$balanced:                        #33cd5f !default;
$energized:                       #ffc900 !default;
$assertive:                       #ef473a !default;
$royal:                           #886aea !default;
$dark:                            #444 !default;
*/

// The path for our ionicons font files, relative to the built CSS in www/css
$ionicons-font-path: "../lib/ionicons/fonts" !default;

// Include all of Ionic
@import "www/lib/ionic/scss/ionic";

// Include Ionicons
@import "www/lib/ionicons/scss/ionicons";

@import "mixins";
@import "listing/listing";
```

It works locally in the browser and in emulator, but i cannot upload app:
```bash
ionic upload

Uploading app...
Error upload response: SyntaxError: Unexpected token < (CLI v1.3.2)
``` 

If I remove `ionicons` i can upload app with no problem.

Please let me if you need any additional information. I can grant access to my private repo as well ;)

**Comment by mlynch** [comment]
Did you modify the ionic.project file? Make sure app_id is empty. Try that
first and let me know if it works. Also make sure to run ionic login before
everything.

On Sun, Jan 18, 2015 at 11:12 PM, Roman Minkin <notifications@github.com>
wrote:

> Hi guys,
>
> Happens for me after i added ionicons with command
>
> ionic add ionicons
>
> Info
>
> ionic info
>
> Your system information:
>
> OS: Mac OS X Yosemite
> Node Version: v0.10.26
> Cordova CLI: 4.2.0
> Ionic CLI Version: 1.3.2
> Xcode version: Xcode 6.1.1 Build version 6A2008a
> ios-sim version: 3.1.1
>
> I also changed ionic.app.scss we i can use ionicons fonts:
>
> /*To customize the look and feel of Ionic, you can override the variablesin ionic's _variables.scss file.For example, you might change some of the default colors:$light:                           #fff !default;$stable:                          #f8f8f8 !default;$positive:                        #387ef5 !default;$calm:                            #11c1f3 !default;$balanced:                        #33cd5f !default;$energized:                       #ffc900 !default;$assertive:                       #ef473a !default;$royal:                           #886aea !default;$dark:                            #444 !default;*/
> // The path for our ionicons font files, relative to the built CSS in www/css$ionicons-font-path: "../lib/ionicons/fonts" !default;
> // Include all of Ionic@import "www/lib/ionic/scss/ionic";
> // Include Ionicons@import "www/lib/ionicons/scss/ionicons";
> @import "mixins";@import "listing/listing";
>
> It works locally in the browser and in emulator, but i cannot upload app:
>
> ionic upload
>
> Uploading app...
> Error upload response: SyntaxError: Unexpected token < (CLI v1.3.2)
>
> If I remove ionicons i can upload app with no problem.
>
> Please let me if you need any additional information. I can grant access
> to my private repo as well ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/12>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by RomanMinkin** [comment]
Hi @mlynch , yes i did, `app_id` already there, because I already uploaded my app few times. Once I remove `ionicons` from `www/lib` and rebuild with `gulp && ionic build ios` I can upload my app again.


```javascipt
{
  "name": "Sharelocity",
  "app_id": "09aa42b9",
  "gulpStartupTasks": [
    "sass",
    "jade",
    "js",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ]
}
```

**Comment by RomanMinkin** [comment]
@mlynch , I tried empty `app_id` field, still the same error. But in Ionic View app on my iPhone I see now ghost clones, but new  `app_id` do not appear in `ionic.project` file.

**Comment by kurtommy** [comment]
For me whit this:
```
{
  "name": "",
  "app_id": ""
}

```
i get this error

 ✗ name: <ul class="errorlist"><li>This field is required.</li></ul>
Unable to upload app (CLI v1.3.2)

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1

**Comment by tlancina** [comment]
@kurtommy name can't be blank

**Comment by kurtommy** [comment]
@tlancina with name:

Error upload response: SyntaxError: Unexpected token < (CLI v1.3.2)

**Comment by tlancina** [comment]
Yup, the error everyone is getting is from "<h1> 500 Server Error </h1>" or something along those lines I believe. We're in the process of fixing these on the backend, improving error handling in the cli, and making it easier/ more clear what users can and can't configure. 

@kurtommy did you also add ionicons?

**Comment by kurtommy** [comment]
yes but via bower! and commented in the sass @import


Tommaso Rossi
Developer - Front End dev - Hibryd app dev
Skype: kurtommyk
www.rossitommaso.it <http://www.rossitommaso.it/>

Rispetta l’ambiente. Hai davvero bisogno di stampare questa mail?
Please consider the environment – Do you really need to print this email?

Informativa Privacy - Ai sensi del D. Lgs n. 196/2003 (Codice Privacy) si precisa che le informazioni contenute in questo messaggio sono riservate e ad uso esclusivo del destinatario. Qualora il messaggio in parola Le fosse pervenuto per errore, La preghiamo di eliminarlo senza copiarlo e di non inoltrarlo a terzi, dandocene gentilmente comunicazione. Grazie.

Privacy Information - This message, for the D. Lgs n. 196/2003 (Privacy Code), may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this for the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by RomanMinkin** [comment]
@tlancina thanks for the update! I just show **Ionic View** to my buddies, they love it, so do I ;)

**Comment by RomanMinkin** [comment]
Work for me now. Thanks!

**Comment by Mabdylon** [comment]
I had the same problem, and installed ionicons, but it wasn't the problem.

Updated node and it work like a charm !

Thx !

**Comment by MEmmanuel** [comment]
Thx! Updated node and worked perfectly!

**Comment by allen8300** [comment]
I'm playing with Ionic official sample "cutePuppyPics".

I can upload it successfully, but I can't view it on Ionic View App "View Error Status 404".

I followed all official documents and tried all methods on google but still can't solve it.

So what is my ionic.project should be like? Or where I'm wrong?

Please save my life.
