### ISSUE TITLE
 A weird css issue occurs when I conbine tabs and side menus together

### ISSUE THREAD

**Issue by liujia1** [driftyco/ionic-view-issues#121]
I post my problem on http://codepen.io/anon/pen/yNowPd. I have to click the tab vicemap first and click the mainmap tab to make the content show itself correctly. I have no idea why this happens. I don't know if it is a bug or i did the side menus or tabs wrong. Did I miss something ?

**Comment by tlancina** [comment]
Does this only occur in View or is it an issue in the browser as well?
