### ISSUE TITLE
Can't sync app, 500 error

### ISSUE THREAD

**Issue by e-oz** [driftyco/ionic-view-issues#122]
Please share details if you are aware of the issue

**Comment by Samfcabral** [comment]
I'm having the same issue.

**Comment by mattchue** [comment]
Try now. This should be fixed, it was happening to me and I brought it up with @ericb and they said they were on it. All clear from my end, at least.

**Comment by ericb** [comment]
Yup sorry I didn't see this earlier guys. The issue was on our end, but it is cleared up now. Sorry about that guys.

Cheers!
