### ISSUE TITLE
KeyboardDisplayRequiresUserAction or hideKeyboardAccessoryBar doesn't seem to work in Ionic View

### ISSUE THREAD

**Issue by djett41** [driftyco/ionic-view-issues#125]
When building [this](https://github.com/djett41/ionic-filter-bar/tree/master/demo) demo app on Ionic View, I am noticing that the following configuration/customizations are not taking place.  These work as expected on emulator and device.

- config.xml  - iOS KeyboardDisplayRequiresUserAction - keyboard isn't coming up when calling focus()
- $window.cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true); - accesory bar still visible after platform is ready.

The Ionic View app id is ab56e8bd

**Comment by gigocabrera** [comment]
+1

**Comment by tlancina** [comment]
Yup, View just downloads your files from `www`, but won't apply any config.xml preferences.  I think adding KeyboardDisplayRequiresUserAction would be worthwhile thing to add though.

The Keyboard issue is most likely this: https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866, platform ready is incorrectly firing immediately.  You can wrap the `hideKeyboardAccessoryBar` call in a setTimeout, or try the hack mentioned in the issue above.

Closing this for now as neither are bugs.
