### ISSUE TITLE
ionicCacheBuster=83674

### ISSUE THREAD

**Issue by arnoutaertgeerts** [driftyco/ionic-view-issues#127]
I'm getting the following strange error when trying to make a http request using `pouchdb` to my cloudant server. (I'm using pouchdb as a client so no data is stored offline)

```
{
    "line": 9110,
    "column: 29",
    "sourceURL": "file:///var/mobile/Containers/Data/Application/ ... / Library/NoCloud/files/7a9f76ab/lib/ionic/js/ionic.bundle.js?ionicCachebuster=82674"
}
```

Any idea what could be causing this?

**Comment by tlancina** [comment]
The cachebuster is appended to asset URL's by the Ionic CLI to solve #10 and shouldn't be causing any issues.  Take a look at what like 9110 of your ionic.bundle.js file is and see if that gives you any pointers to the cause.
