### ISSUE TITLE
Bluetooth cordova doesn't work in Ionic view

### ISSUE THREAD

**Issue by gregory-yet** [driftyco/ionic-view-issues#128]
Hello,

The is not a real issue but the Bluetooth ngCordova plugin doesn't work in Ionic view, the plugin work well when I install the real .APK on my Android Phone. Can you add the bluetooth plugin to your supported plugin in Ionic view ? Thanks.

PS : I use the integrated bluetooth plugin from ngCordova

**Comment by tlancina** [comment]
We will be looking into bluetooth support for the next round of plugins! (It's been requested a lot)

**Comment by mritchie712** [comment]
Was this ever added?

**Comment by gregory-yet** [comment]
@mritchie712 Idk, but if you want to use bluetooth you need to install the .APK on your phone. In my case, this solution work :)
