### ISSUE TITLE
Ionic View App for Windows Phone ???

### ISSUE THREAD

**Issue by HansS** [driftyco/ionic-view-issues#129]
Is it possible to see in the future a windows phone version of ionic view app?

**Comment by cassioscofield** [comment]
+1

**Comment by tlancina** [comment]
It will probably happen in the future, but isn't a high priority right now.

**Comment by StachuDotNet** [comment]
+1. Is there any way I can help?

**Comment by HansS** [comment]
Hi Stachu,
i will change my phone.I bought an android phone!I got it, Microsoft Windows Phone is not part of the Mobile Open Source platform: Cordova,Phonegap, Ionic!
kind regardsHans

Date: Tue, 24 Nov 2015 13:09:31 -0800

**Comment by victorcarvalhosp** [comment]
+1

**Comment by davidnmbond** [comment]
+1

**Comment by maclbb** [comment]
+1

**Comment by nazrdogan** [comment]
+1

**Comment by BarbaLoira** [comment]
+1

**Comment by BarbaLoira** [comment]
+1

**Comment by gourabxz** [comment]
+1
