### ISSUE TITLE
add support for indexedDB

### ISSUE THREAD

**Issue by mnewmedia** [driftyco/ionic-view-issues#13]
So i'm new to cordova, angular, ionic and so on ;)

But i think i get the error:
`typeError: null is not an object (evaluating: 'indexedDB.open')`
because it opens it in the `UIWebView` instead of the `WKWebView`. 

i also added this plugin but it didn't help:
https://github.com/Telerik-Verified-Plugins/WKWebView

I'm using pouchdb which handles this indexeddb stuff..

best regards

**Comment by tlancina** [comment]
You can use the SQLite plugin for PouchDB on iOS: http://pouchdb.com/adapters.html#pouchdb_in_the_browser.
