### ISSUE TITLE
Upload Fails with Errror - App ID f41158dd does not exist

### ISSUE THREAD

**Issue by laurencehoess** [driftyco/ionic-view-issues#137]
I initially uploaded my app on Oct 14, 2015. Now when I try to upload my changes, I get the following error, even though my app id is clearly showing in the dashboard as (ID f41158dd)

```
An error occurred uploading your application - App ID f41158dd does not exist (CLI v1.6.5)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Mac OS X Yosemite
Node Version: v4.1.1
Xcode version: Xcode 7.1 Build version 7B91b 
```

**Comment by laurencehoess** [comment]
This seems to be similar to issue #10 but even after remove the App Id, I can't find the new upload in the deployment web page.

**Comment by laurencehoess** [comment]
I figured out the problem. I somehow was logged in under a different account in the CLI. Maybe add the current account to the message about the App ID not existing?

**Comment by Persevierance** [comment]
I did the same because l had mistakenly deleted the app from ionic view. i fixed it by deleting `.io-config.json` and deleting the app id from `ionic.config.json` to be like  `{
  "name": "{{AppName}}",
  "app_id": "",
  "v2": true,
  "typescript": true
}`

Then l tried to upload again.
