### ISSUE TITLE
Login invalid.. No errors. Works elsewhere except with Ionic View App..

### ISSUE THREAD

**Issue by shotbyabel** [driftyco/ionic-view-issues#149]
Happy New Year All! 

The issue is that I can't login to my app while using Ionic View on my iPhone.

I am under the impression that Ionic View is ONLY to preview static apps? My login $http code hits a development server url and it works fine on the emulators, browser and both iOs and Android devices.

When I run the ionic upload command in my terminal everything goes well and I can view the login screen on my iPhone for the app BUT it does not accept my login credentials or any.

Why is this and what can I do?

The reason I don't have any code to show is because I am not getting errors and the login on my app works fine everywhere else.

Any ideas?.. thanks!

**Comment by simplesmiler** [comment]
You can try to check out server logs. Does the request actually hit the API endpoint?
And there is always [window.onerror](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) too.

**Comment by tlancina** [comment]
Hey @shotbyabel did you figure this out? If there's some View specific behavior we should either fix it or document it.

I would guess that it's related to platform.ready firing immediately, similar to: https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866, which is causing the page to error and become unresponsive.

Going to close this, but let me know if you have some way to reproduce the issue and I can take a look, thanks!
