### ISSUE TITLE
Invite not working: "Incorrect E-mail" being displayed

### ISSUE THREAD

**Issue by alejandromagnorsky** [driftyco/ionic-view-issues#153]
My invitees are getting an error after receiving an invite, signing up and trying to use that invite (with the same email, of course):

https://lh5.googleusercontent.com/-P71UQiHJbMI/VrEq74_RA5I/AAAAAAAABb4/QfPIj-Z6hVI/w692-h369-no/Capture.PNG

**Comment by tlancina** [comment]
Hey @alejandromagnorsky is this still an issue?

**Comment by alejandromagnorsky** [comment]
Hadn't see this happening again in a while. So I assume is fine now.

**Comment by tlancina** [comment]
Ok great, going to close this then. Let me know if it happens again and we can re-open, thanks!
