### ISSUE TITLE
Facebook popup is blank

### ISSUE THREAD

**Issue by onkar-infoobjects** [driftyco/ionic-view-issues#154]
Following error shown wile calling openfb js login method.
Error in Success callbackId: InAppBrowser52373944 : ReferenceError: loginWindow_loadStopHandler is not defined.

Earlier it was working, recently this issue happened.

**Comment by tlancina** [comment]
Hey thanks for the issue. inAppBrowser (the plugin used for facebook oauth) isn't supported by View at this time, but you can request it be added here: #15.
