### ISSUE TITLE
Social Login via Ionic View App results in whitescreen

### ISSUE THREAD

**Issue by chris-barnett** [driftyco/ionic-view-issues#155]
Hi,

I am trying to integrate Firebase social login (Facebook, Google and Twitter) into my Ionic App.

When I run this in my browser everything works as expected, I can login and get redirected.

When I send this over to the Ionic View App on my iPhone, I am able to login via the social site but never get redirected and I'm left on a whitescreen.

I have the cordova inappbrowser plugin installed.

Many thanks

**Comment by tlancina** [comment]
Hey thanks for the issue. InAppBrowser isn't supported by View at this time, but you can request it be added here: #15.

**Comment by faeezshaikh** [comment]
Same problem. Any ETA on this pls?
