### ISSUE TITLE
fileopener2 dont work in ionic View

### ISSUE THREAD

**Issue by gwellner** [driftyco/ionic-view-issues#156]
I checked $cordova ondeviceReady and got the following object.

output $cordova under Ionic View:
``` json
{"plugins":{"fileextras":{},"barcodeScanner":{"Encode":{...}, ...}
```
dont works.

if i package the apk and install it on my android the output is
``` json
{"plugins":{"fileopener2":{}} ...}
```
and it works.

tested on Android.

**Comment by tlancina** [comment]
Hey thanks for the issue. That plugin isn't supported by View at this time, but you can request it be added here: #15.
