### ISSUE TITLE
Display inline video in Ionic View

### ISSUE THREAD

**Issue by Codematic-AppDev** [driftyco/ionic-view-issues#163]
Any chance the Ionic View app can be updated to display online video? I assume I can only submit one issue at a time but if not, maybe the View app could also apply the status bar style, if possible?

**Comment by tlancina** [comment]
Hey thanks for the issue, I'm going to close this as a dup of https://github.com/driftyco/ionic-view-issues/issues/126.

**Comment by allen8300** [comment]
@tlancina  why you close #126 because of #163;
At the same time, you close #163 because of #126;
