### ISSUE TITLE
Unit testing app (httpBackend, services, diresctives ,DOMs)

### ISSUE THREAD

**Issue by yasuda22m** [driftyco/ionic-view-issues#167]
Hi,

I wanted to unit test my app. i tried and watched more videos for this purpose, But i could't get the best way to test. While i'm using **IONIC (not ionic2)** and using karma, jasmine, angular-mocks to unit test.

**Comment by tlancina** [comment]
Hey this is the issue tracker for [Ionic View](http://view.ionic.io/), you might want to try asking on the forums: https://forum.ionicframework.com/.
