### ISSUE TITLE
Ionic 2  Ionic View

### ISSUE THREAD

**Issue by AimiForgan** [driftyco/ionic-view-issues#169]
After running ionic upload in the cmd line I am getting the  following error:

WARN: No 'upload:before' gulp task found!
If your app requires a build step, you may want to ensure it runs before upload.

Then if I go into Ionic View my app screen is blank.

Can you please help.

**Comment by tlancina** [comment]
Try adding `gulp.task('upload:before', ['build']);` to your gulp file and then run `ionic upload`

**Comment by AimiForgan** [comment]
Hi yes that is already in my gulp file sorry should have said that.

**Comment by tlancina** [comment]
Great, glad it's working. Closing since it wasn't a View bug.
