### ISSUE TITLE
Add support for Evothings Bluetooth plugin

### ISSUE THREAD

**Issue by jmkao** [driftyco/ionic-view-issues#17]
I currently use the Evothings bluetooth stack (and also their app pointed to inside my ionic project) to do rapid development iterations on iOS (since the emulator doesn't support bluetooth, rapidly doing iterations direct to device is a must).

I would love to invert my workflow and use ionic view to do iterations since Evothings has no build or push-to-server tooling (particularly a convenient central server like yours).

**Comment by tlancina** [comment]
Closing this, added to the plugin requests issue.
