### ISSUE TITLE
ionic-cloud Camera plugin not working in ionic View app

### ISSUE THREAD

**Issue by joshgarwood** [driftyco/ionic-view-issues#170]
Hey guys!  I'm loving ionic-view thus far, but one issue that I ran into today was that the Camera plugin doesn't seem to work inside of the IonicView app on android. Though I feel like I may be doing something wrong... To reproduce

1. Install the latest ionic2 beta
2. Install @ionic/cloud-angular
3. Install the camera plugin: **ionic plugin add cordova-plugin-camera**
4. Create a component similar to the one below.
5. Upload the app using **ionic upload**

Whenever I'm in the IonicView app and the **"takePicture"** function is called,  the error handler gets executed and all I see is:  **"There was an error: {}"**

If I generate an actual apk and install that on my phone it works like a charm. Am I missing something? I'm using **ionic2 Beta8** and the latest version of the ionicView app.

Thanks so much for your time!

```
import {Component} from '@angular/core';
import {NavController, Alert, ActionSheet} from 'ionic-angular';
import {PaymentInfoPage} from '../payment-info/payment-info';
import {Camera} from 'ionic-native';

@Component({
    templateUrl: 'build/pages/user/image-upload/image-upload.html',
})
export class ImageUploadPage {
    private pictureData = null;

    constructor(public nav: NavController) {

    }

    private takePicture(sourceType) {
        Camera.getPicture({
            destinationType: Camera.DestinationType.DATA_URL,
            sourceType: sourceType,
            encodingType: Camera.EncodingType.PNG,
            quality: 100,
            targetHeight: 800,
            targetWidth: 800,
            allowEdit: true,
            saveToPhotoAlbum: true,
            correctOrientation: true,
            cameraDirection: Camera.Direction.FRONT
        }).then((imageData) => {
            this.pictureData = 'data:image/jpeg;base64,' + imageData;
        }, (err) => {
            let alert = Alert.create({
                title: 'Picture error',
                subTitle: 'There was an error saving your photo.  Please try again.' + JSON.stringify(err),
                buttons: ['OK']
            });
            this.nav.present(alert);
        });
    }
}
```

**Comment by tlancina** [comment]
Hey @joshgarwood could you provide some more details about the device you're running it on? I just pasted this code into the [Ionic Conference App](https://github.com/driftyco/ionic-conference-app) and it worked fine for me. Thanks!

**Comment by joshgarwood** [comment]
Hey @tlancina! Thanks so much for the quick response!  Yea, I'm running on an HTC 1x with Android v6.  

Are there any additional configuration steps that I need to do here?  I would feel more like I had done something wrong if it wasn't working whenever I generate the apk, ha.

Thanks again!

**Comment by tlancina** [comment]
@joshgarwood could you check the permissions for View? I did have something weird happen when I just tested right now and the Camera permission got messed up. I was testing on a Nexus 6P also running Marshmellow, so in theory it's the same.

Some other thoughts on trying to narrow this down: uninstalling and reinstalling View, calling `navigator.camera.getPicture` with callbacks instead of the Ionic Native wrapper to see if that works instead, testing it in a completely blank app except for the camera call.

**Comment by jamesvsshark** [comment]
Hey Josh,

You ever find out what the issue was? I also am having issue with ionic view plugins not working on an android device.  

Thanks!

**Comment by joshgarwood** [comment]
Hey @jamesvsshark Unfortunately I didn't.  Since Android makes it so easy to distribute via apk, we ended just giving the apk to our testers which solved a lot of our issues.  

Sorry I couldn't be of more help!

**Comment by jamesvsshark** [comment]
No problem. Thanks for the quick reply.

I just stumbled on what appears to be a similar issue related to ionic platform web client being deprecated and instead to use ionic cloud. 

Going to mess around with this and will reply here if that's the case.

**Comment by jamesvsshark** [comment]
Hey Josh,

That was the case!

I followed the migration guide http://docs.ionic.io/migration.html, essentially removing the ionic-platform-web-client stuff and all is good with the plugins using Ionic view with an Android device.

**Comment by tlancina** [comment]
Hey thanks @jamesvsshark, glad you figured it out. I'm going to close this for now, but let us know if you're still having issues, thanks!
