### ISSUE TITLE
11th August Update locks iPad to Portrait View

### ISSUE THREAD

**Issue by IllusionVK** [driftyco/ionic-view-issues#179]
After my iPad auto updated to version 1.1.0 it no longer allows Ionic View to rotate to landscape mode.  Things i've double checked: 
- my iPad screen rotation lock is NOT on (ie other apps and the home screen are able to be displayed in Landscape)
- Undertaken a reboot of the iPad and issue remains.  
- Tried toggling iPad screen rotation lock to on to see if Ionic view had the logic reversed - makes no differences either on or off.
- Tried opening Ionic View when i had iPad rotation locked to landscape, but it ignores it and only presents both app list and apps in portrait mode.
- Tried rotating the iPad both left and right - makes no difference.
- Running iOS 9.3.2 (not the very latest, but I'm not aware of major API changes in the latest version by Apple that would cause a backwards compatibility issues)

**Comment by simplesmiler** [comment]
You can try to check the presence of `<preference name="orientation" value="..." />` line in `config.xml`, maybe they got it working.

**Comment by IllusionVK** [comment]
thanks @simplesmiler, i forgot to add this to my list.  Applications (that i expected to rotate) did not have `orientation` set in `config.xml`  ie. screen should be allowed to rotate.

**Comment by tlancina** [comment]
Thanks for the issue, we'll be looking into allowing orientation to be configured on a per app basis, since different apps have different needs.

**Comment by pickettd** [comment]
I'm having this issue too. Thanks for the note @tlancina but I don't quite follow what you mean. Are you saying that we should be able to configure Ionic View and all applications to be landscape?

In IV 1.1.0 on my iPad with iOS 9.3.2 I can't get Ionic View (itself or apps) to go to landscape orientation at all. It is just stuck in portrait. Ionic View on Android does work for changing orientation between landscape and portrait though.

**Comment by tlancina** [comment]
That's because the latest release of View on iOS doesn't support orientation change.

Some apps don't want to support orientation change, some do. Whichever one we choose will be incorrect for some apps, unless we allow each app to specify the correct behavior. There isn't a way to do this in place yet, but if we, for example, uploaded config.xml along with the `www` folder this would allow apps much more control over their experience in View, as long as the preference changes can be made at runtime (orientation can I'm fairly sure).

**Comment by ubaidseth** [comment]
Any updates to this? Since I only preview my app in Landscape - this messed everything up for me. 

If I build and send to the the app store - will it still be portrait or landscape?

**Comment by tlancina** [comment]
This seems to be more of an issue for apps that _need_ landscape (like in @ubaidseth's case), than apps that probably _shouldn't_ rotate, so as soon as the Android update is out we'll cut a small iOS release to restore all orientation styles.

**Comment by tlancina** [comment]
Orientation is back in View for iOS 1.1.1 :) Closing for now, let us know if you're still having issues, thanks!
