### ISSUE TITLE
How to load more data from remote server when page is scroll to top?

### ISSUE THREAD

**Issue by sleeper01** [driftyco/ionic-view-issues#182]
As what I said in the title,when the new datas are rendered,I want to hash on the item before last load.
![image](https://cloud.githubusercontent.com/assets/4557307/17835866/c5f34550-67b1-11e6-99ab-22ceb4bd2711.png)

**Comment by tlancina** [comment]
Hey these are the issues for the Ionic View app, you might want to try asking on the Ionic Forums: https://forum.ionicframework.com/.
