### ISSUE TITLE
Error 401 when opening Ionic View with iOS 10

### ISSUE THREAD

**Issue by cballock** [driftyco/ionic-view-issues#187]
Hi guys.
I am having a 401 error when trying to open Ionic View with iOS 10.
I already deleted and re-installed the Ionic View app but the problem persists.
Any ideas about this error? 
Thanks.

Carlos.

**Comment by tlancina** [comment]
Have you tried logging out and signing back in?

**Comment by cballock** [comment]
Yes, I also tried that.

**Comment by tlancina** [comment]
Ahh yeah can confirm, something's up. Will take a look first thing Monday.

**Comment by cballock** [comment]
Thanks, Tim!

**Comment by lionel5116** [comment]
I am having the same issue as well, It's only for iOS, Android is fine..

**Comment by pixelone** [comment]
Yeah same here iOS both 9 and 10 having this 401 issue.  It did work fine hours ago though, maybe server related?

**Comment by yannpiot** [comment]
I'm having the same issue on iOS.

**Comment by gsws-github** [comment]
I am having the same issue on IOS 9 as well :(

**Comment by tlancina** [comment]
Yeah looks like there was a server configuration issue, it should be
resolved now. Going to close, but let us know if you're still having
problems, thanks!

**Comment by cballock** [comment]
For me its ok, now, Tim. Thanks!
