### ISSUE TITLE
Ionic View - Android latest version - Cannot connect to server

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-view-issues#188]
_From @cnngraphics on September 27, 2016 17:1_

#### Short description of the problem:
Load Ionic View App
Enter email
enter password
Logged in and --> "No apps yet", but I do have 6 apps when I look at to online version of ionic account

"PULL down to refresh" ==> Unable to connect to server. Status code: 404

What happened to the "ionic upload" command. 

Where are my uploaded apps that I used to view in ionic view app?

_Copied from original issue: driftyco/ionic#8237_

**Comment by jgw96** [comment]
_From @cnngraphics on September 27, 2016 17:4_

Looks like in the Playstore, others are experiencing this issue and are suggesting to switch to phonegap build.

Anyone else having issues?

**Comment by tlancina** [comment]
Hey @cnngraphics thanks for the issue, I believe there were some server side issues last week but they should have been resolved. Are you still getting this error?

If so, could you tell me the version of View you're using as well as the device and Android version, thanks!

**Comment by cnngraphics** [comment]
Yes! @tlancina, I reinstall the app and all is looking good!

Thanks!

**Comment by tlancina** [comment]
Ok great, I'm going to close this then. Let us know if you're still having issues, thanks!
