### ISSUE TITLE
Facebook login returned a security warning

### ISSUE THREAD

**Issue by pixnlove** [driftyco/ionic-view-issues#19]
Hi Ionic team,

I tried your Ionic View app and I discovered a problem with the Facebook login. I am using [OpenFB micro-library](https://github.com/ccoenraets/OpenFB). The Facebook connect works as well in the emulator but when I'm trying to log me with your app it's returning this :

![img_2212](https://cloud.githubusercontent.com/assets/2814767/6045686/7983d04e-ac9c-11e4-8135-de9d0d281b5b.png)

I think the problem comes from :

        `loginWindow = window.open(FB_LOGIN_URL + '?client_id=' + fbAppId + '&redirect_uri=' + oauthRedirectURL + '&response_type=token&scope=' + scope, '_blank', 'location=no');

        // If the app is running in Cordova, listen to URL changes in the InAppBrowser until we get a URL with an access_token or an error
        if (runningInCordova) {
            loginWindow.addEventListener('loadstart', loginWindow_loadStartHandler);
            loginWindow.addEventListener('exit', loginWindow_exitHandler);
        }`

**Comment by tlancina** [comment]
View is already running in an inAppBrowser, so I'm not sure that the
inAppBrowser plugin will work from within any apps you load.

Thanks for bringing this up, I'll take a look and see if we can get
inAppBrowser plugin support working.

In the meantime, could you maybe get the access token via Ajax instead?

**Comment by smithgt** [comment]
+1 for InAppBrowser
Just spent several hours trying to figure out why I wasn't getting a location bar for the InAppBrowser through Ionic View yet it worked fine in the emulator.

**Comment by tlancina** [comment]
Closing this, added to the plugin requests issue.

**Comment by benjis** [comment]
Had the same issue when running IonicView on iOS with OpenFB. 
@pixnlove, @smithgt, have you guys find a solution for this problem yet?

**Comment by pixnlove** [comment]
@benjis, I finally chose [TestFlight Beta Testing](https://developer.apple.com/testflight/) to invite users to test my app. It's a powerful tool made by Apple (so only for IOS app) : more complicated to deploy but better experience (a real app on your phone).

**Comment by elhamsarikhani** [comment]
@benjis does TestFlight Beta support the plugins such as inAppBrowser as well?

**Comment by ignacio-chiazzo** [comment]
@pixnlove @tlancina  Anyone found a solution for this Issue? I have a IONIC project, if I run on emulator I have not problem, however if i run the app on IONIC VIEW with my IPhone I get the same problem "secure warning....", and if I run my app in a android device it work fine.

Another question, How can i get my ipa file in order to run the app into TestFlight

**Comment by dmarcos89** [comment]
HI @ignacio-chiazzo @tlancina @pixnlove, have you find a solution to this? I am facing the same issue when trying to login into my app using Ionic View, but on the browser works perfectly...
Thanks
