### ISSUE TITLE
on click works in emulator and browser but not ionic view

### ISSUE THREAD

**Issue by JuanAntelo** [driftyco/ionic-view-issues#195]
Hi,

I am unable to navigate to one of my apps pages only in my ionic view app for ios. In the iOS emulator and browser there are no issues

**Comment by amuramoto** [comment]
@JuanAntelo Hi! Can you please provide the code that is causing the issue?

**Comment by JuanAntelo** [comment]
Hi @amuramoto 

I was able to fix this issue by debugging the device. I found out that it was a file path issue. My code referenced a template called

`src/templates/template.html`

but in my file system it was 

`src/templates/Template.html`

Matching the two together solved this issue on the device for me.
