### ISSUE TITLE
Login not working - Status 403

### ISSUE THREAD

**Issue by renanmzmendes** [driftyco/ionic-view-issues#20]
Login for  Ionic View  iOS app is returning status code 403 when trying to login.

I don't know if this is the place to create such an issue, but I didn't know where else to go and I get no meaningful search results on Google.

**Comment by renanmzmendes** [comment]
Deleting the application and reinstalling it did the trick

**Comment by docherty** [comment]
I had this issue too. A bit more detail:
- I created an apps.ionic.io account with a password in my desktop browser
- opened Ionic View app on iOS and logged in (no problem)
- visited apps.ionic.io on desktop browser and changed password
- closed Ionic View app on iOS device
- opened Ionic View on second iOS device and logged in with new password no problem
- returned to first device and re-opened Ionic View app
- tried to log in with new password & received error 403 (tried several times but same issue)

I then re-installed the Ionic View app on the original device and was able to log in using the new password.

I hope this helps,
James

**Comment by vett09** [comment]
Deleting the Ionic View app on my iPhone and reinstalling it did the trick for me as well.

**Comment by tlancina** [comment]
Login problems _should_ be fixed with the latest release, please re-open if you're having issues still!
