### ISSUE TITLE
Deleting app on Ionic View should requires similar steps as transferring

### ISSUE THREAD

**Issue by netcell** [driftyco/ionic-view-issues#202]
Please require the same steps on Ionic Cloud website for deleting apps on Ionic View.

I accidentally deleted my in-production app today on Ionic View, and looking for help on driftyco/ionic-cloud-issues#245 

While this is totally my fault, I think it would help a lot if deleting an app requires entering the app name, similar to transferring app.

**Comment by netcell** [comment]
Sorry, I think this one should be on ionic cloud since it's the issue for both ionic cloud and ionic view

**Comment by tlancina** [comment]
I think it's definitely a valid issue for View as well. Just a note though
- the option to delete your app from View will be going away in a future
release.
