### ISSUE TITLE
No scroll on apps list

### ISSUE THREAD

**Issue by renanmzmendes** [driftyco/ionic-view-issues#21]
I can't see all my apps because there is apparently no way of scrolling the content.
I am using an iPhone 4S, is that a potential problem?

**Comment by tlancina** [comment]
Hmm that shouldn't be happening! It sounds like it could be a keyboard bug,
sometimes if the keyboard events don't fire correctly on login it will lock
up the scroll view.

Any tips on how I could reproduce this?

**Comment by renanmzmendes** [comment]
I have deleted the app and reinstalled again and it worked. I couldn't reproduce the bug since then... Could it have something to do with the storage space available? My phone was completely full (I couldn't even take a picture...)

Anyway, if you'd like to close this issue, go ahead. It doesn't seem to be reproducible.

**Comment by tlancina** [comment]
Closing for now, feel free to re-open if you have issues in the future.
