### ISSUE TITLE
No apps showing up when logged in

### ISSUE THREAD

**Issue by ccasad** [driftyco/ionic-view-issues#22]
I've created a couple of ionic apps (one from OSX and one from Linux) and ran the ionic upload command, which asks for my email and password. I enter those and it says Logged In and then it says Uploading app. When I go to Ionic View and log in using the same email and password all I ever see is the splash screen saying I don't have any apps. I've tried to create a separate account in case there was something initially wrong with the first account but the second has the same issues.

**Comment by mlynch** [comment]
Chris, when you do the upload, is it showing "Successfully uploaded
(ID_HERE)"?

Have you modified ionic.project and the app_id field by hand? If so, remove
it and try again

On Mon, Feb 9, 2015 at 12:35 PM, Chris Casad <notifications@github.com>
wrote:

> I've created a couple of ionic apps (one from OSX and one from Linux) and
> ran the ionic upload command, which asks for my email and password. I enter
> those and it says Logged In and then it says Uploading app. When I go to
> Ionic View and log in using the same email and password all I ever see is
> the splash screen saying I don't have any apps. I've tried to create a
> separate account in case there was something initially wrong with the first
> account but the second has the same issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/22>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by ccasad** [comment]
It says "Successfully uploaded" and that's it. No id after the word "uploaded". I haven't touched the ionic.project file, but the app_id field has a blank value. At what point is this app_id field supposed to be set?

**Comment by tlancina** [comment]
What does `ionic info` say?

**Comment by ccasad** [comment]
I ran ionic info and it then told me to update via npm to the latest. I did
that, ran the build and performed the upload and it worked. I think I'm
good now. Thanks a lot. Very cool framework you all have created!

**Comment by tlancina** [comment]
Awesome, glad things worked out :) Going to close this, but feel free to re-open if you're still having issues.
