### ISSUE TITLE
The camera does not seem to work fine on ionic view at my iphone5

### ISSUE THREAD

**Issue by dreamline2** [driftyco/ionic-view-issues#24]
http://forum.ionicframework.com/t/test-camera-on-ionic-view/16360

I can't open my camera, but it can work fine when use other method to upload test app. ex: https://monaca.io/

**Comment by tlancina** [comment]
What version of View are you using? Camera support was just added a couple days ago.

**Comment by dreamline2** [comment]
ok, I just updated latest version. it can work fine. thx ：）
