### ISSUE TITLE
Opening Ionic View app itself returns a 401 status code

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic-view-issues#26]
Also, when trying to delete an app inside Ionic View app, a 401 status code is received.

**Comment by mlynch** [comment]
Try killing the app and reopening it, or reinstalling it. Does that fix it?


On Wed, Feb 18, 2015 at 7:21 PM, Keith D. Moore <notifications@github.com>
wrote:

> Also, when trying to delete an app inside Ionic View app, a 401 status
> code is received.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/26>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by RomanMinkin** [comment]
I had the same issue, i did relogin inside the IonicView app.

**Comment by keithdmoore** [comment]
@mlynch: reinstalling resolved the two issues.  I was actually in the process of trying that when you mentioned to try that.
