### ISSUE TITLE
Unable to get out of InAppBrower when opening a window

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic-view-issues#27]
When I try to open a window using the InAppBrowser cordova plugin, I am unable to close the window. 
Here is the app I am trying to run https://github.com/trendicity/trendicity

Just goto the Side Menu and click on Login and enter your Instagram credentials.  This appears to error out for some reason and you get stuck being logged into Instagram and unable to return to the app.  This only happens inside Ionic View.

**Comment by tlancina** [comment]
Hey InAppBrowser is on the list of plugins to support in the future. You can take a look at current requests and add your own in https://github.com/driftyco/ionic-view-issues/issues/15.

**Comment by keithdmoore** [comment]
Ok.  Thanks for pointing that out.   I guess I just assumed they were all available.
