### ISSUE TITLE
Re-uploading deleted app

### ISSUE THREAD

**Issue by MartinMa** [driftyco/ionic-view-issues#28]
Recently the feature to delete an app was added. I did so. But now I can't seem to re-upload the app.

The CLI tool says "Successfully uploaded", but I can't see it in my list. When I try to add the app ID manually, I seem to get an old version of the app.

**Comment by tlancina** [comment]
Hey thanks for the issue, we're aware of this and are working on it.  In the meantime, to force the server to regenerate your app ID you can change app_id to "" in your ionic.project file.

**Comment by tlancina** [comment]
Should be fixed now! Let us know if you're still having issues.

**Comment by MartinMa** [comment]
:+1: Thanks for the quick response. It works now!

**Comment by mubasshir** [comment]
I know this has been closed but i'm still facing same issue. Any fix for this?

**Comment by dominiqueh** [comment]
Also having this problem.. When I try 'ionic link APPID' and then ionic upload it fails to upload with the error message "An error occurred uploading your application - App ID 196e00cd does not exist (CLI v2.2.2)"

Any fix or am I doing something wrong?

**Comment by tlancina** [comment]
Hey @dominiqueh can you email help@ionic.io, if your app is deleted support will get you sorted out.

**Comment by trinvh** [comment]
Look into ionic.config.json and change app_id to empty "" then problem gone
