### ISSUE TITLE
Custom control using SVG does not update

### ISSUE THREAD

**Issue by finleysg** [driftyco/ionic-view-issues#30]
I have several directives that leverage SVG to respond to user clicks and provide visual feedback. The template for two of them look something like this

```
div class="approach-shot-container">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="approach_shot" viewBox="0 0 340 340" preserveAspectRatio="xMinYMin meet">
        <defs>
            <circle id="ball" r="6" stroke="#000000" fill="#FFFFFF" stroke-width="0.5"></circle>
        </defs>
        <g id="green">
            <path data-location="40" class="missed_green" d="M37.69 ... and so on ...
			<more paths... />
        </g>
        <g id="shots">
        </g>
    </svg>
</div>
```

Basically, I capture the user click, convert to an svg location, and then insert a reference to the "ball" circle (see the defs) into the shots group. It's a shot tracker, like for basketball.

Works great in local development using Chrome on Windows. Once uploaded to ionic view, it works only for the first click. Any changes or new instances are not captured -- I see only the original "shot".

Seems like I'm either getting bit by caching, or the behavior is just different within the ios webview. Until I can get hold of a mac to attach my phone, I am at a loss as to how to troubleshoot this.

Any ideas about what I might try?

**Comment by mnewmedia** [comment]
maybe same problem like #10 
Clear Data, close App (double click home button,two finger up) should do it for the moment.

**Comment by finleysg** [comment]
No, I'm afraid that's not a fix for this. I did run into css/js caching problems, which are easy enough to work around as you noted.

I know that my event handler is handling the click/tap, but the svg dom manipulation doesn't appear to happen -- or the view is simply not refreshed to reflect the dom changes.

The directive as it now exists is here: https://github.com/finleysg/stats-mobile/blob/master/www/src/rounds/approach/approach-result-input.js

**Comment by finleysg** [comment]
The first answer is, there is nothing wrong with SVG rendering and manipulation within the UIWebView (as far as I know). I simply had a dom call that works in Chrome, but not in the UIWebView.

The second answer regarding how to troubleshoot this sort of thing: find a mac to run the emulator.
