### ISSUE TITLE
Scrolling broken on iPhone 4

### ISSUE THREAD

**Issue by lennycartier** [driftyco/ionic-view-issues#31]
Hello,

in Ionic View app, the "Terms and condition" & "Privacy policy" pages do not scroll so we can't read the entire document and we are stuck at the top.

Platform : iPhone 4 / iOS 7.1.2

Thanks,

lenny

**Comment by lennycartier** [comment]
My bad, it used to not scroll, but now it scrolls...

**Comment by tlancina** [comment]
Not your bad! This is almost definitely a keyboard bug on iPhone 4's, after logging in scrolling is broken, but is easily solved by reloading the app.

**Comment by tlancina** [comment]
I'm pretty sure this is the same as https://github.com/driftyco/ionic-view-issues/issues/21, leaving this one open in case other people have the same issue.
