### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by wxyyxc1992** [driftyco/ionic-view-issues#33]
I register and upload my app yse ionic upload, But I can't find my app in ionic-view. Where can I confirm my app whether to upload successfully?

**Comment by keithdmoore** [comment]
You might try setting the app id to empty string in ionic.project and try: ionic upload again.  Also, you might try uninstalling Ionic View and reinstalling.

**Comment by wxyyxc1992** [comment]
Thank You I will try it again

**Comment by tlancina** [comment]
Closing this, if you're still having problems feel free to open an issue in the cli repository: https://github.com/driftyco/ionic-cli.
