### ISSUE TITLE
French translation for Playstore description

### ISSUE THREAD

**Issue by lennycartier** [driftyco/ionic-view-issues#37]
Please replace the wrong english->french translation by : "Ionic View permet de charger, visualiser et tester les applications que vous créez grâce à Ionic"

Thanks and keep up the awesome job !

lenny

**Comment by tlancina** [comment]
Interesting... that must be automatically translated, I'll see if I can get
it fixed, thanks!

Any suggestions on a correct translation?

**Comment by lennycartier** [comment]
I did a suggestion in my report above. You can be sure it is french :-)

Maybe the beginning of the solution here to add your translation : https://support.google.com/googleplay/android-developer/answer/113469?hl=en

**Comment by tlancina** [comment]
Ah désolé, I misread it as the incorrect translation. Weirdly the French google play errors for me, so I can't load it for some reason.

Can you say "app" instead of "application" in French? The short description on the play store is limited to 80 characters so I was going to make it: "View permet de charger et visualiser les apps que vous créez grâce à Ionic".  Does that sound ok?

**Comment by pbernasconi** [comment]
I don't think `charger` is the right word to use -- `télécharger` would be better.

Perhaps:

`Ionic View vous permet de facilement télécharger et visualizer les apps crées avec Ionic Framework`

**Comment by tlancina** [comment]
Thanks! Any ideas on a shortened ( < 80 chars) version of that? Does "Ionic View vous permet de télécharger et visualizer les apps crées avec Ionic" sound ok?

**Comment by lennycartier** [comment]
You van replace apps by "applis"

Le 4 mars 2015 12:51:01 PST, Tim Lancina <notifications@github.com> a écrit :
>Thanks! Any ideas on a shortened ( < 80 chars) version of that? Does
>"Ionic View vous permet de télécharger et visualizer les apps crées
>avec Ionic" sound ok?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/driftyco/ionic-view-issues/issues/37#issuecomment-77244365

-- 
Lenny Cartier / l.cartier@free.fr
datanotes.org

**Comment by tlancina** [comment]
Updated, thanks guys! Should be reflected in the Play Store in the next few hours.

**Comment by lennycartier** [comment]
Sorry to bother you again... please change "crées" by "créées". I know...it's french... 

Thanks,

lenny

**Comment by tlancina** [comment]
Thank goodness we had one character remaining for the description! Thanks @lennycartier
