### ISSUE TITLE
App not using most recent upload

### ISSUE THREAD

**Issue by squeaky-clean** [driftyco/ionic-view-issues#38]
Platform: Android 4.4 and iOS 8 (have not tested other versions)

When using Ionic View, the app will usually display an outdated version of my app. I can do 'ionic upload' and get a success message. 'Sync to Latest' and see the app's modified time change in Ionic View. But when I try to view the app, it is an older version that I had uploaded earlier. I've started adding alert() calls in my app.js to display the version, and it is often lagging by many uploads.

I've tried clearing the app's data, deleting the app (or both), and killing the Ionic View process on my android phone. I can delete the app, see it disappear in Ionic View, upload again, see it appear with the latest time, and it will still be an older version of my app. I can do 'ionic serve' or 'ionic build' and they will display the up-to-date app correctly.

It eventually does work, but I'm not sure how. If I need to just wait a long enough time between uploads or what. As it is now, about 3/4 of my uploads seem to not actually change anything.

edit: Tested on iOS-8, same issue. Syncing showed "Already Up To Date", but the viewed app was over a day old. Clearing App Data and redownloading (twice) fixed the issue.

**Comment by tlancina** [comment]
Dup of https://github.com/driftyco/ionic-view-issues/issues/10.
