### ISSUE TITLE
Add feature to remember apps that you have entered an App ID for?

### ISSUE THREAD

**Issue by ynnejasdf** [driftyco/ionic-view-issues#47]
Hi Ionic Team! 

I've been enjoying using Ionic View to share and test apps with fellow team members and testers. However, it is rather cumbersome that each time they close the Ionic View App, they have to check and re-enter AppID upon entering again. There is no section that records AppID they entered before either.  

Is there any way that Ionic View can remember AppID entered before? OR is there a workaround? Or can this feature be added (and if so potential timeline?) 

Really appreciate your thoughts as it really can be a big help! 

Thanks so much,
Jen

**Comment by mlynch** [comment]
Coming soon! We are going to let you invite a user to an app to check it
out.


On Mon, Mar 16, 2015 at 12:01 PM, ynnejasdf <notifications@github.com>
wrote:

> Hi Ionic Team!
>
> I've been enjoying using Ionic View to share and test apps with fellow
> team members and testers. However, it is rather cumbersome that each time
> they close the Ionic View App, they have to check and re-enter AppID upon
> entering again. There is no section that records AppID they entered before
> either.
>
> Is there any way that Ionic View can remember AppID entered before? OR is
> there a workaround? Or can this feature be added (and if so potential
> timeline?)
>
> Really appreciate your thoughts as it really can be a big help!
>
> Thanks so much,
> Jen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/47>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by ynnejasdf** [comment]
Thanks Max! Any potential timeline? Mainly for our planning for a bigger test. Thanks.

**Comment by ynnejasdf** [comment]
And before then, is there a way I can customise the AppID so that it is memorable? I can already do quite a lot with that. Thanks so much. Really appreciate your help.

**Comment by ynnejasdf** [comment]
Hi Max! I see the "ionic share EMAIL" prompt in the terminal just now! Very exciting. Gave that a try to my Ionic View account. However when we logged in, my colleague and I didn't see the shared app. What is supposed to happen? Thanks again.
