### ISSUE TITLE
Requires ability to delete an app permanently

### ISSUE THREAD

**Issue by pbernasconi** [driftyco/ionic-view-issues#5]
I have duplicates which I'd like to delete, but there's no functionality to do this.

Should be an easy thing to do, and help with storage issues.

**Comment by RomanMinkin** [comment]
+1 here, i have 3 ghost apps now i would love to get rid of ;)

**Comment by lmolema** [comment]
+1

**Comment by desmondcain** [comment]
+1 Need to do some cleaning up but there isn't any way to delete the apps.

**Comment by albertpak** [comment]
+1

**Comment by kskenneth** [comment]
should be a must have function. Thanks Ionic team!

**Comment by eruecco87** [comment]
Please add this, I cannot delete an app and I just created one to test the service that I do not want listed there.

**Comment by mlynch** [comment]
It's coming in the next release for iOS once apple approves, then on the
dashboard.

On Wed, Feb 4, 2015 at 8:06 PM, Oscar Viquez <notifications@github.com>
wrote:

> Please add this, I cannot delete an app and I just created one to test the
> service that I do not want listed there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/5#issuecomment-72981417>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by tlancina** [comment]
In there with the latest release

**Comment by andreafdaf** [comment]
I'm still having this problem with some apps... one can be deleted, another keeps coming back every time after deletion (both dashboard and android)
