### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by kristianbenoit** [driftyco/ionic-view-issues#56]
Hi, I use DatePicker from ngCordova, which is not supported by ionic-view.

**Comment by Goundar** [comment]
I confirm, with ionicview, i have this error : `"Error "Cannot read property 'show' of undefined""` when i try to call `$cordovaDatePicker.show(options)`. On real device, i have no problem.

**Comment by jtbairdsr** [comment]
+1 for DatePicker support in ionic-view

**Comment by tlancina** [comment]
Hey thanks for the issue. That plugin isn't supported by View at this time, but you can request it be added here: #15.
