### ISSUE TITLE
Add support for Cordova-SQLitePlugin

### ISSUE THREAD

**Issue by ionixjunior** [driftyco/ionic-view-issues#6]
The Cordova-SQLitePlugin not supported by Ionic View.

Plugin site: https://github.com/brodysoft/Cordova-SQLitePlugin

**Comment by timothyha** [comment]
Yes, please add this plugin.  Is there any specific issue with adding it?

**Comment by ninjamonkno1** [comment]
+1 for the SQLite plugin please and 10+ for getting it done asap ;)

**Comment by tlancina** [comment]
So it looks like the plugin needs to reference an existing database file.  Considering that we'll be allowing groups/organizations to have apps in the future and the potential for conflicts between apps, I think it would pretty unwise to have a shared db file across all apps. 

If there was a database that was created for the life of viewing an app and then destroyed on close would that still allow you to preview the functionality of any apps? Remember View is not meant for testing, but to share a preview of your app across devices.

**Comment by ninjamonkno1** [comment]
Is it not just a case of having the plugin present in the app? I don't follow why it needs a database, its loads fine in my project without a database and used to create one if its not present.

**Comment by ionixjunior** [comment]
@tlancina - This plugin creates a database file on the device file system based on the name configured on the application. Then, I guess it is not possible to control the database file on the life of viewing an app, because Ionic View does not know the database's name of the application to control it.

**Comment by tlancina** [comment]
@ionixjunior thanks, in the docs it looked like you had to have a db file created already, but that makes sense that it would just make one if it wasn't already there.

The main issue I can think of is sandboxing the databases from each other, since if two apps use the same name there would be issues.

**Comment by ninjamonkno1** [comment]
Not sure if this will help you in this but I have just tested my app on the phonegap developer app and it works fine and creates the databases etc using this plugin.

**Comment by ionixjunior** [comment]
@ninjamonkno1 this plugin works perfectly. The problem of the plugin is only inside on Ionic View.

**Comment by ronyrun** [comment]
Hi any update on this subject ?

**Comment by tlancina** [comment]
The plugin is in the next release, which is currently waiting for review
from apple. It should be available sometime next week I would think.

**Comment by tlancina** [comment]
Latest release is out with the SQLite plugin in there, let me know if you have issues!

**Comment by venkatpolisetti** [comment]
I have just uploaded my test app that works alright with SQLite database on an IOS emulator but sits at at the splash screen not doing anything. 

Does ionicview  has support for apps that have SQLite databases? 

As per the comment about it looks like it has.  

What am I missing?

Thanks
