### ISSUE TITLE
External http request not working

### ISSUE THREAD

**Issue by CheetahDev** [driftyco/ionic-view-issues#65]
Hi,

As we don't have any Mac at the moment to build our app for the iOS platform, we're using the Ionic View App. It's a very convenient solution to test and show our prototype. However, since we started the "dynamic" step (static data ==> JSON WebServices request), we're facing a problem. On Android (native), it works fine. But when it comes to the Ionic View App (iOS or Android), the $http.get seems to fail, no data are retrieved. I didn't find any testing solution to monitor the Ionic View App (such as the Chrome Devices Inspect for example), so I'm not able to tell exactly what's going wrong.

Regards

**Comment by CheetahDev** [comment]
Some new findings:

- GET request randomly fails, even on the Android native app (Chrome Inspect tool gives us : Method:GET | Status:(failed) | Type:Pending | Initiator:ionic.bundle.js:18110)
- Our WS request uses https
- I tried to request https://cors-test.appspot.com/test, it randomly fails too
- Request worked one time on the Ionic View App (Android)

**Comment by CheetahDev** [comment]
It's really really really strange... Sometimes it works on the native Android app, sometimes not, sometimes it works on the Ionic View App on my Android device, sometimes not,... but I never got a response on the iOS' Ionic View App.

I tried with other WS, such as a weather WS, it works well when the endpoint is http://... but it fails or works when the endpoint is https://... (depending on the provider).

**Comment by CheetahDev** [comment]
Issue solved. Our wifi network was blocking access to ... internal stuff (even if it was exposed via an external endpoint...). Was pretty hard to find without any log or even a simple 404...

**Comment by shadesoflight** [comment]
cordova-plugin-whitelist can sometimes solve $http issues on android also

**Comment by birbal007** [comment]
facing the same problem. i have developed the app in ionic 2 and its apk working fine in android devices but in ios my app not able to hit the Exernal API. what could be the problem

**Comment by rogeliotrejo13** [comment]
I have the same problema with Ionic 3 in android, only in android I need use encodeuricomponent() in all my parameters with  import { HTTP } from '@ionic-native/http';  plugin, and en iOS this cause problems. Any solution for this issue in android?
In iOS the plugin import { HTTP } from '@ionic-native/http';  works perfectly.
Cordova CLI: 6.5.0  
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.9.0
Xcode version: Xcode 8.3 Build version 8E162

**Comment by LtotheWT** [comment]
Good day @birbal007, did u found the solution ? @@
