### ISSUE TITLE
Getting out of your demo app

### ISSUE THREAD

**Issue by educatedrisk** [driftyco/ionic-view-issues#71]
Installed Ionic View onto Samsung Note 3 android phone.  Was able to login and upload the demo start app.  

The issue I had was when I was jumping around inside the demo app, with "Status, Chats, Account" then trying to get back to the Ionic-View main screen where it lists the apps.  I found that I couldn't go back with my back button, there was no menu items from the menu button on my phone. 

Actually had to exit Ionic-View to get back to the list of apps.

Hopefully you can add a way to exit from your apps easier.

Great work on all that you have done.

Cheers

**Comment by quanghoc** [comment]
So I assumed you used 3 fingers swipe down and not working either? As it is the way to get back.

In my case some app with scroll will take over the 3-finger swipe instead and Ionic View cannot detect it. It is very inconsistent

**Comment by tlancina** [comment]
Yeah I don't think the swipe is working on Android, just the back button,
which is obviously an issue in many cases.

Any preferences on an alternate way to exit the app that you could change
in the settings? I was thinking like a long press or something similar so
it wouldn't conflict with other swipe gestures people may be using.

**Comment by kumaro** [comment]
is this still not solved ? how do I exit from the app on android?

**Comment by leob** [comment]
I think you can't. On Android the 3 finger gesture doesn't work. Just press the back button 200 times or kill the app and restart it.

**Comment by stefek99** [comment]
Is it "fixed" now?

I don't have Android device handy and I need to give instructions to a client...

```Kill the app and start again```

**Comment by neojato** [comment]
@tlancina Sadly this hasn't been fixed yet, but an idea would be to either enable us to double-tap the back button and/or long-press the back button to exit our apps and return to the list. Thoughts?

**Comment by gparsloe** [comment]
iPhone 6: I had to turn Zoom off (Settings --> General --> Accessibility --> Zoom) in order to get the 3 finger swipe down to exit the Ionic View app.
