### ISSUE TITLE
Default Ajax-Request Timeout in the ionic-view app

### ISSUE THREAD

**Issue by pavax** [driftyco/ionic-view-issues#72]
I'm using the ionic-view on my ipad mini. I'm having a problem making an ajax-request to an server that is not responding (for example if the server is not up and running).

Example (simplified):
```javascript
   doPing() {
            return this.$http.get('http://192.168.1.100:8080/api/ping')
                .then(function (successResponse) {
                    alert('Received Data');
                }, function (errorResponse) {
                    alert('Error');
                });
        }
```
**Steps to reproduce:**

1. Started my Backend-Server on Port 8080 that handles the "/api/ping" Request
2. Click on a Button that triggers the mentioned doPing() function
3. The alert 'OK' will show up "immediately"
4. Stop the Backend-Server
5. Click the Button again
6. Nothing happens (also not after several minutes)
7. Close the App with the "three-fingers-swipe-down" gesture 
8. The alert 'Error' appears now

**Expected:**
The alert 'Error' response should appear after a reasonable amount of time.

Everything works fine in FF, Chrome, IE and within the Ripple-Emulator

**Ideas:**
Has this something to do with the cordova config value 'loadUrlTimeoutValue' that might be set in the ionic-view config.xml to an infinite or big value?

**Comment by rsweny** [comment]
Try this, it is working for me:

$http.get(myurl, { timeout: 10000 });

details: https://docs.angularjs.org/api/ng/service/$http

**Comment by pavax** [comment]
I added the following HttpInterceptor 

```javascript
(function () {
    "use strict";

    angular
        .module('ui.common')
        .factory('HttpInterceptor', HttpInterceptor);

    // @ngInject
    function HttpInterceptor(CONFIG) {
        function request(config) {
            config.timeout = CONFIG.DEFAULT_REQUEST_TIMEOUT;
            return config;
        }

        return {
            request: request
        };
    }

}());
```
...and configured the HttpInterceptor in my app.js:
```javascript
.config(function httpProviderConfig($httpProvider) {
        $httpProvider.interceptors.push('HttpInterceptor');
})
```
...and it works fine. Thanky you!

PS: This timeout-problem also occurs on android. But the given 'fix' using the angularjs timeout setting on $http should work on all platforms.
