### ISSUE TITLE
Orientation on ios

### ISSUE THREAD

**Issue by hsdk123** [driftyco/ionic-view-issues#74]
Hi, I'm noticing that on ios, the orientation of the app is stuck to portrait (whereas what I want is landscape) - the orientation can be changed on the Android version, but not on the iOS. 

It would be great if this could be supported as designs can't properly be tested.

**Comment by ewagnerdesign** [comment]
I'm having the same issue.  Orientation can be changed in emulator but not in the Ionic View app.

**Comment by simplesmiler** [comment]
Ionic View did not support orientation on iOS prior to 1.0.6.
