### ISSUE TITLE
Unexpected token < (CLI v1.3.2)

### ISSUE THREAD

**Issue by billmn** [driftyco/ionic-view-issues#8]
I have updated Ionic CLI and executed <code>ionic upload</code>

This is the response:
![schermata 2015-01-15 alle 19 42 08](https://cloud.githubusercontent.com/assets/779534/5764008/1d476d66-9cef-11e4-9044-49451119a93e.png)

**Comment by mlynch** [comment]
Did you do ionic login first?

**Comment by billmn** [comment]
Sure

**Comment by billmn** [comment]
Oh ok ... I think is for this, right?

![schermata 2015-01-15 alle 20 52 57](https://cloud.githubusercontent.com/assets/779534/5765281/8a89d356-9cf8-11e4-9912-4ff0afb45fee.png)

**Comment by tlancina** [comment]
Could you post the contents of running `ionic info` please?

Also what does your ionic.project file look like? 

Thanks!

**Comment by billmn** [comment]
Hey Tim, here Ionic info:
<pre>
Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.30
Cordova CLI: 4.1.2
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 2.0.1 
</pre>

and ionic.project file content:
![schermata 2015-01-15 alle 23 29 40](https://cloud.githubusercontent.com/assets/779534/5768204/e38fb446-9d0e-11e4-9002-c780abfd68fb.png)

**Comment by mlynch** [comment]
app_id can't be set by you. Remove that and try again.

I wonder how we can fix this because it's a constant problem. Tim, any ideas?

**Comment by billmn** [comment]
Thank you guys ... without "app_id" value it works fine! ;)

**Comment by kurtommy** [comment]
in my project.ionic i have only this:

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.2
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: 3.1.1 

{
  "name": "",
  "app_id": ""
}

and if i try to run ionic upload i receive:

Error upload response: SyntaxError: Unexpected token < (CLI v1.3.2)

**Comment by magic890** [comment]
It worked for me using this configuration:

```json
{
  "name": "TestApp",
  "app_id": "",
  "gulpStartupTasks": [
    "sass",
    "watch"
  ],
  "watchPatterns": [
    "www/**/*",
    "!www/lib/**/*"
  ]
}
```

then execute ```ionic upload```
and ```app_id``` was automatically updated using an hash code.
Now I'm able to see my app using Ionic View on the smartphone.

**Comment by kurtommy** [comment]
i'm using grunt not gulp, this is your ionic.project file? @magic890

**Comment by henry74** [comment]
Using a blank app_id doesn't appear to work.  Removing the app_id entirely gives an "X App undefined not found" error.

**Comment by RomanMinkin** [comment]
@henry74 I opened similar issue https://github.com/driftyco/ionic-view-issues/issues/12 since this one was closed. And describe my situation take a look maybe it's relevant to your case...

**Comment by shawnzxx** [comment]
Same here this is my ionic.project

{
  "name": "MobileApp",
  "app_id": ""
}

It's very strange, the first time I run ionic upload it works perfect, but after that I try to upload the app again, I always got the Unexpected token < (CLI v1.3.2)  error.

**Comment by tlancina** [comment]
Fixed this today, should be rolling out soon.

**Comment by billmn** [comment]
@shawnzxx Delete on cloud side is not available for now

**Comment by mlynch** [comment]
Mr. Tim is rolling it out over the course of the next several time periods

On Wed, Jan 21, 2015 at 12:10 AM, Davide Bellini <notifications@github.com>
wrote:

> @shawnzxx <https://github.com/shawnzxx> Delete on cloud side is not
> available for now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/8#issuecomment-70789289>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by tlancina** [comment]
Ah that's what I get for responding over email, @shawnzxx there's no way to delete yet, I was referring to fixing https://github.com/driftyco/ionic-view-issues/issues/12. Sorry for any confusion, you will be able to remove apps from View in the next release however.

**Comment by mladenp** [comment]
I am also getting same unexpected token error, my app_id is blank and ionic info:
    OS: Windows 8
    Node Version: v0.11.13
    Cordova CLI: 4.2.0
    Ionic CLI Version: 1.3.2
What should we update to fix this error?

**Comment by mlynch** [comment]
"The key to a JSON parsers heart, is an unexpected token, at an unexpected
time."

On Wed, Jan 21, 2015 at 8:49 AM, Mladen Petrovic <notifications@github.com>
wrote:

> I am also getting same unexpected token error, my app_id is blank and
> ionic info:
> OS: Windows 8
> Node Version: v0.11.13
> Cordova CLI: 4.2.0
> Ionic CLI Version: 1.3.2
> What should we update to fix this error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/8#issuecomment-70849746>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by shawnzxx** [comment]
@tlancina Thank you for your quick replay.  I am looking forward to see the next release.

**Comment by mladenp** [comment]
It works now, yeey :+1:

**Comment by tlancina** [comment]
@shawnzxx wait time depends on the app you're trying to view. If it's a big project or there are a lot of files (ie ionicons), it'll take a while to download and unzip.  Although 2 minutes seems does seem like a very long time to me. Feel free to open another issue with how to reproduce if you think it's a bug.

**Comment by bgosalci** [comment]
Thank you @mlynch this (app_id can't be set by you. Remove that and try again.) solved my problem.

**Comment by ianseyer** [comment]
Just a note to future readers: This is marked as merged, however the issue persists for me ever after following steps.

I have changed app_id to an empty string, removed the property entirely, and opened a fresh clean test project, `platform add ios` and `ionic upload`, to the same failure.

My solution was to try:
`ionic link` which, according to the help dialog: `Sets your Ionic App ID for your project.` 

It then prompted me for an `App ID,` to which I replied `--reset.`

**Comment by tlancina** [comment]
@ianseyer if you're experiencing this it's probably a regression of some kind.  Could you open a new issue with steps to reproduce the issue, including the output of the `ionic info` command?

**Comment by ianseyer** [comment]
@tlancina the issue is difficult to reproduce, as it seems to simply go away at some point.

If the error message is anything to go by, then it is a malformed **response** from the Ionic upload servers.

**Comment by shamilovtim** [comment]
Still an issue here. Have attempted all of the solutions referenced. Emptied the `App ID` string. Cleared my `~/.ionic/` cache. Running latest Node, Ionic, and Cordova client and server side.

**Comment by emileae** [comment]
I got the same problem, but then running ionic buils ios / ionic build android sorted it out for me... maybe something to do with ionic prepare?

**Comment by shamilovtim** [comment]
This was caused by an older ionic cli version installed globally on my system 

npm -g install was not updating the CLI and the same version would remain. To resolve I uninstalled global ionic, removed ionic folder from where global npm modules are stored, cleared npm cache, restarted my machine. After restart npm -g install ionic and I had the latest ionic CLI and the problem was resolved.

**Comment by rohan2934** [comment]
![error](https://cloud.githubusercontent.com/assets/13061832/14206820/730be646-f833-11e5-99fa-aae2f03c75da.png)


When i define a variable in ionic2 like 
class abc {
    name: string;
}
It gives me unexpected token shown in picture.

**Comment by wbhob** [comment]
What I found is that there was a problem building (a git merge conflict was not rendering the plugins correctly). So a quick `ionic state reset` fixed it for me.

**Comment by avinash683** [comment]
if i run ionic start app blank-----------
/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.start_wizard (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/index.js:25:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/lib/ionic/start.js:13:30)
    at Module._compile (module.js:460:26)


/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/start_wizard.js:99
      ps.stdout.on('data', (data) => {
                                  ^^
Unexpected token => (CLI v2.2.3)

Your system information:

Cordova CLI: 7.0.0 
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v0.12.18
Xcode version: Not installed
