### ISSUE TITLE
bug: Ionic View doesn’t display local images

### ISSUE THREAD

**Issue by perrygovier** [driftyco/ionic-view-issues#82]
_From @maketroli on April 18, 2015 15:53_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>That's my issue now, I am working on my app, when I do ```$ ionic serve``` everything display properly in the browser, but once I build the app and then do ```$ ionic upload```, I go to the Ionic View app, and I have 2 issues, non of the images are displaying, and also I have an Audio tag which is for a Live Streaming, and it is no working also.

So, what is going on here ?

![img_1593](https://cloud.githubusercontent.com/assets/8395866/7216119/b8f2d8ea-e5b0-11e4-9163-8c9d5de8247a.PNG)

</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3553_

**Comment by tlancina** [comment]
Dup of #54.
