### ISSUE TITLE
Blank app, on Android, doesn't render right

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-view-issues#85]
I made a virgin app, Blank template, and uploaded it. When I view it on my Android, the UI is not right for the header. Looks like a CSS file didn't load. I'd give you an exact error but my device isn't showing up in adb devices currently because HTC hates me I think.

**Comment by tlancina** [comment]
Nice catch, are you using a beta version of the cli? It looks like upload for android broke with the fix for #10.  Should be fixed now, although it might not make it up to npm for a couple days. I'll close this when the new version is out.

**Comment by cfjedimaster** [comment]
Yes - beta3 I believe.

On Fri, Apr 24, 2015 at 12:11 PM, Tim Lancina <notifications@github.com>
wrote:

> Nice catch, are you using a beta version of the cli? It looks like upload
> for android broke with the fix for #10
> <https://github.com/driftyco/ionic-view-issues/issues/10>. Should be
> fixed now, although it might not make it up to npm for a couple days. I'll
> close this when the new version is out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/85#issuecomment-95994727>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by reenku** [comment]
Here i have posted an issue. http://forum.ionicframework.com/t/graphics-and-font-display-issue/26568
does this the same as yours?
PS. I am also using HTC.

**Comment by tlancina** [comment]
Hey going to close this as I believe the underlying issue - CLI uploads - was resolved.
