### ISSUE TITLE
cordova is not defined

### ISSUE THREAD

**Issue by ildarkayumov** [driftyco/ionic-view-issues#86]
I want to save images to device filesystem. I use for it the next code:
```javascript
    self.saveImage = function(url) {
      var targetPath = url;
      $ionicPlatform.ready(function() {
        if (window.cordova) {
          targetPath = cordova.file.dataDirectory + (/\w+\.\w+$/).exec(url);
          $cordovaFileTransfer.download(url, targetPath, {}, true);
        }
      });
      return targetPath;
    }
```
It is working when i run it on real device or emulator using: ionic run android.
But when i try to upload it to ionic view and run I receive the next errors:

```javascript
Failed to load resource file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/cordova.js
TypeError: Cannot read property 'dataDirectory' of undefined
    at file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/js/services.js:194:36
    at file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/ionic.bundle.js:43957:19
    at Object.ionic.Platform.ready (file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/ionic.bundle.js:2117:9)
    at Object.self.ready (file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/ionic.bundle.js:43955:26)
    at Object.self.saveImage (file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/js/services.js:191:22)
    at Object.self.applyChanges (file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/js/services.js:211:23)
    at file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/js/services.js:232:18
    at file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/angular/angular-resource.js:626:34
    at processQueue (file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/ionic.bundle.js:21108:27)
    at file:///data/data/com.ionic.viewapp/files/files/bcbc9e29/lib/ionic/js/ionic.bundle.js:21124:27 ionic.bundle.js:19526
```
If i remove part of save to file it will work perfect.

Thank you.

**Comment by tlancina** [comment]
File and file transfer plugins aren't supported yet.

**Comment by ildarkayumov** [comment]
Ok, thank you @tlancina

**Comment by sebestenyb** [comment]
I have a slightly different issue.
It's actually `window.cordova` what is undefined running in Ionic View.
```
$ionicPlatform.ready(function() {
     $log.debug('[app] - ready() :: window.cordova: ' + window.cordova);
}
```

produces the following log running in Ionic View:

```
ionic.bundle.js?ionicCachebuster=21327: Line 20306 : [app] - ready() :: window.cordova: undefined
```

**Comment by tlancina** [comment]
@sebestenyb yeah this is an annoying gotcha with View right now.  Cordova is injected into the web view after the page has loaded, meaning Ionic will run before Cordova is defined.  I've been looking into the best options to remedy this for the past couple days, but in the meantime you can try replacing your ionicPlatform.ready's with 1-2 second $timeouts to wait for Cordova and the plugins to initialize.

**Comment by sebestenyb** [comment]
Yeah, that's what I ended up with.
Would be nice if Cordova would have an event when it's ready.

**Comment by tlancina** [comment]
Luckily it does! The `deviceready` event is fired on the document "once page has fully loaded, all constructors have run and cordova info has been received from native side."

This is the event that ionic is not waiting for because it sees there is no Cordova object and assumes we're in a browser, not a web view.

**Comment by tlancina** [comment]
And instead of using $timeout, in case it helps anyone else: https://github.com/driftyco/ionic-view-issues/issues/52#issuecomment-99250866

**Comment by sebestenyb** [comment]
But if we add `<script>window.phonegap = {}</script>` then it doesn't work in the browser, I guess, as the `$ionicPlatform.ready` even won't fire at all?

**Comment by bilalakil** [comment]
Hello everybody,

I'm in need of some advice/confirmation regarding this issue. @tlancina earlier mentioned:

> File and file transfer plugins aren't supported yet.

I'm working on an app whose primary focus is to save a parsed representation of a download file to localStorage and allow users to access it offline. The point here is that the downloading component is critical to the usage of the app - it's useless without it.

Is it still the case, 10 months later, that file and file transfer plugins are not supported?

If so, is there any way at all you can imagine dealing with this problem for Ionic View? Without it it will be much harder for me to share the prototypes with my client for review and to end-users for pre-release feedback.

Thanks!
