### ISSUE TITLE
bug: doesn't ionic view  include crosswalk - chromium?

### ISSUE THREAD

**Issue by mhartington** [driftyco/ionic-view-issues#88]
_From @isaldarriaga on April 24, 2015 13:23_

**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When webview is not an option, you probably use crosswalk either for performance or functional reasons.

After uploading my app to ionic view, I see it's not working at all. The app is using angular material.

2 questions:

- If i set my app to use crosswalk, it will load the engine in ionic view?
- Is it possible to debug the app running in ionic view with chrome remote debugging?

Thanks,

Ivan.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#3608_

**Comment by mhartington** [comment]
This issue was moved to driftyco/ionic-view#55

**Comment by adamduren** [comment]
@mhartington I can't see the status of the issue it was moved to. Any update on this I have the same questions.

**Comment by jpike88** [comment]
I can't see that link either. Why would they make that repo private?

**Comment by jpike88** [comment]
Six months later, still nothing. And that link doesn't work. Are you guys serious?

**Comment by jpike88** [comment]
So Ionic View is basically a piece of crap on most Android devices that don't have a decent webview. And it also seems that the Ionic team is either all dead, on holidays, or most likely being really really bad at their jobs. The fact that the Ionic View repo is private, and this one is basically a complaints box nobody looks at is infuriating and is an extremely lazy way to develop anything. Screw Ionic, I'll use Angular Material.

**Comment by mlynch** [comment]
@jpike88, your abusive attitude isn't welcome here.

Regardless, Crosswalk for View is on our roadmap. We are working hard to improve Ionic proper (including much improved Android perf in 2) and we've let View sit for a bit while we do that. Closing and locking for now.
