### ISSUE TITLE
uploaded my app success, open in ionic view app screen is blank

### ISSUE THREAD

**Issue by kcferguson1** [driftyco/ionic-view-issues#91]
i have uploaded my app successfully using the CLI.  
i go to the ionic view app on my iphone.
select download my app.
then i see blank screen.

**Comment by tlancina** [comment]
What version of the cli are you using? Upload was broken in 1.3.21 I
believe so try updating to 1.3.22 if you haven't already.

**Comment by MaicolBen** [comment]
Happens the same to me with 1.3.22

**Comment by tlancina** [comment]
@MaicolBen any way you could email me the app id so I can check out what's going on? (tim at drifty com) If not no worries! I want to see if the cachebuster fix is mangling the html in your index.html, since we've had a couple reports of unintended changes to the markup.

**Comment by rakelblujeans** [comment]
Any updates here? I'm having the same issue. My app otherwise works fine using 'ionic serve/run'.

**Comment by kofronpi** [comment]
+1

**Comment by pinsmile** [comment]
+1...

**Comment by alexfigueiredo** [comment]
+1

**Comment by druc** [comment]
In my case I was missing a plugi.. so make sure you have all the plugins installed -  `ionic plugin`
If that doesn't work, try the old fashion way - comment everything and place alerts to see where it breaks.

**Comment by tlancina** [comment]
Hey going to close this as it seems it was resolved, thanks!
