### ISSUE TITLE
Please add cordovaToast support

### ISSUE THREAD

**Issue by stevenpack** [driftyco/ionic-view-issues#96]
Great app. I love the ionic upload, then sync workflow. Very quick, very simple.

I just spent a bit of time getting my first cordova plugin working, which is toast. Worked on the emulator, but not the view app. I just read in the blog post that not all plugins are supported yet so:

1) Please add toast
2) I'd suggest prioritising the ngCordova plugins in order of popularity.

**Comment by sasokovacic** [comment]
+1

**Comment by ngoclinh15994** [comment]
+1

**Comment by zapnap** [comment]
This would be super helpful.

**Comment by ngoclinh15994** [comment]
Dear Giang,
đây là file đính kèm :)
Thân !

2015-07-06 21:12 GMT+07:00 Nick Plante <notifications@github.com>:

> This would be super helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-view-issues/issues/96#issuecomment-118868332>
> .
>



-- 
*NGUYỄN NGỌC LINH*
Mobile    : 84-(0)1648542412
Skype      : ngoclinh15994                      Email    :
ngoclinh15994@gmail.com
Facebook : *https://www.facebook.com/vianhlagio1594
<https://www.facebook.com/vianhlagio1594>*
