### ISSUE TITLE
Error sharing: Error: Parse Error 

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-view-issues#98]
I upload my app without any problem and can view it myself on the view app. I can also deploy on android 4.4 without any problem. However, sharing is not working right now. I get a parse error. 

Uploading app...
Successfully uploaded (0******6)

Share your beautiful app with someone:

$ ionic share EMAIL

C:\Users\jack\ionic\test>ionic share ****@gmail.com
Sharing app 0*******6 with ****@gmail.com
Error sharing: Error: Parse Error (CLI v1.3.22)

Your system information:

OS: Windows 8.1
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.2
Ionic CLI Version: 1.3.22

**Comment by bobalazek** [comment]
I also have this problem:

Error sharing: Error: Parse Error (CLI v1.5.5)

Your system information:

Cordova CLI: 5.1.1
Ionic Version: 1.0.0-beta.14
Ionic CLI Version: 1.5.5
Ionic App Lib Version: 0.2.2
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.2 LTS 
Node Version: v0.12.4

**Comment by bobalazek** [comment]
OK, I found out that the problem in my case was, that I "forgot" to upload the app first (which means, that It wasn't even initialized on the server)... So yeah, silly me...
