### ISSUE TITLE
ionicview app not showing the firebase data (app works fine in desktop chrome)

### ISSUE THREAD

**Issue by AheadAhmed** [driftyco/ionic-view-issues#99]
js code
---------------------------------------------------------------------------------------------------------------
angular.module('ionicApp', ['ionic','firebase'])

.controller('getdata', function($scope) {
 $scope.input = {}; 
 $scope.employees = {};
 $scope.myData =  new Firebase("https://kfushiboat.firebaseio.com/");
  

  $scope.myData.on ('value', function(snapshot){
  $scope.employees = snapshot.val();
  $scope.$apply();
  });

});

---------------------------------------------------------------------------------------------------------

**Comment by AdrienDC** [comment]
+1
